#!/bin/bash

set -e

UNDER_ON=`tput smul` || UNDER_ON=''
UNDER_OFF=`tput rmul` || UNDER_OFF=''
BOLD=`tput bold`  || BOLD=''   # Select bold mode
REV=`tput rev` || REV=''      # Select bold mode
BLACK=`tput setaf 0` || BLACK=''
RED=`tput setaf 1` || RED=''
GREEN=`tput setaf 2` || GREEN=''
YELLOW=`tput setaf 3` || YELLOW=''
BLUE=`tput setaf 4` || BLUE=''
MAGENTA=`tput setaf 5` || MAGENTA=''
CYAN=`tput setaf 6` || CYAN=''
WHITE=`tput setaf 7` || WHITE=''
RESET=`tput sgr0` || RESET=''


# pesy-JSON.sh prints out all the fields in the form of:
# ["key"] value
# where value may be an array.
# pipe the output of that to
#
# cat package.json | ./pesy-JSON.sh | sed -n 's;\["peasyLibs"\][[:space:]]*\(.*\);\1;p'
#
# Where (in that case) you would be extracting the value for `peasyLibs` field.
# use [[:space:]] character class to ensure mac/linux compat.
#
# You can extract deeper fields by searching for fields like ["esy","build"].

# Need to avoid spinning up node every build command.
# MD5_OF_PACKAGE
# $cur__target_dir has some problems right now.
# $fixed_cur__target_dir="$cur__original_root"

# We can build out of source, then simply copy over the .merlin files because
# those are whitelisted! We can also prepare them.

# The two modes:
# update: Update the jbuild files based on package.json
# build:  Perform the build from files updated in update mode.
# Only way to determine that we are part of actual build vs. command line
# update mode is by looking for noprofile.


SHOW_HELP="false"
if [[ "$1" == "help" ]]; then
  SHOW_HELP="true"
else
  if [[ "$1" == "--help" ]]; then
    SHOW_HELP="true"
  fi
fi

if [[ "$SHOW_HELP" == "true" ]]; then
  printf "\\n%spesy%s%s: Your simple esy assistant.%s" "${BOLD}${GREEN}" "${RESET}" "${BOLD}" "${RESET}"
  printf "\\n"
  printf "\\n  %spesy --help%s " "$BOLD" "$RESET"
  printf "\\n    Show this help screen."
  printf "\\n"
  printf "\\n  %spesy%s " "$BOLD" "$RESET"
  printf "\\n    Running pesy in a fresh directory will help you set up an esy project."
  printf "\\n"
  printf "\\n  %sesy pesy%s (in a project that uses esy)" "$BOLD" "$RESET"
  printf "\\n    Once you have an esy project, 'esy pesy' will keep your project up to date."
  printf "\\n    (make sure pesy is listed as a devDependency)."
  printf "\\n\\n\\n"
  exit 0
fi

if [ -z "${cur__name}" ]; then
  # Running bare on the command line, not in an esy environment.
  HAS_JSON="false"
  if [ -f  "${PWD}/package.json" ]; then
    HAS_JSON="true"
  else
    if [ -f  "${PWD}/esy.json" ]; then
      HAS_JSON="true"
    fi
  fi
  if [[ "$HAS_JSON" == "true" ]]; then
    printf "\\n%sIncorrect Usage:%s" "${RED}${BOLD}" "${RESET}"
    printf "\\n"
    printf "\\npesy should only be run via 'esy pesy', unless you want to create a new project"
    printf "\\nin a fresh directory. This does not appear to be a fresh directory because"
    printf "\\nit contains a package.json or esy.json file.\n\n"
    printf "\\nType esy --help for more assistance.\n\n"
    exit 1
  fi

  printf "\\n%sCreating new package at ${PWD}/package.json.%s\\n" "${GREEN}${BOLD}" "$RESET"
  printf "\\n"
  printf "Enter new package name: " 
  read ANSWER
  # Gnu uppercasing extensions to sed don't exist on mac.
  PACKAGE_NAME_CAMEL=$(echo "${ANSWER}" | perl -pe 's/([a-z0-9])-([a-zA-Z0-9])/$1\U$2/g')
  PACKAGE_NAME_CAMEL_UC=$(tr '[:lower:]' '[:upper:]' <<< "${PACKAGE_NAME_CAMEL:0:1}")${PACKAGE_NAME_CAMEL:1}
  NAMESPACE="${PACKAGE_NAME_CAMEL_UC}"
  PUBLIC_LIB_NAME="${ANSWER}.lib"
  printf "{\\n"                                                              >> "${PWD}/package.json"
  printf "  \"name\": \"%s\",\\n" "$ANSWER"                                  >> "${PWD}/package.json"
  printf "  \"version\": \"0.0.0\",\\n"                                      >> "${PWD}/package.json"
  printf "  \"description\": \"My Project\",\\n"                             >> "${PWD}/package.json"
  printf "  \"esy\": {\\n"                                                   >> "${PWD}/package.json"
  printf "    \"build\": \"pesy refmterr dune build -p #{self.name}\"\\n"    >> "${PWD}/package.json"
  printf "  },\\n"                                                           >> "${PWD}/package.json"
  printf "  \"buildDirs\": {\\n"                                             >> "${PWD}/package.json"
  printf "    \"lib\": {\\n"                                                 >> "${PWD}/package.json"
  printf "      \"name\": \"%s\",\\n" "${ANSWER}.lib"                        >> "${PWD}/package.json"
  printf "      \"namespace\": \"%s\"\\n" "${PACKAGE_NAME_CAMEL_UC}"         >> "${PWD}/package.json"
  printf "    },\\n"                                                         >> "${PWD}/package.json"
  printf "    \"bin\": {\\n"                                                 >> "${PWD}/package.json"
  printf "      \"name\": \"%s\"\\n" "${PACKAGE_NAME_CAMEL_UC}.exe"          >> "${PWD}/package.json"
  printf "    }\\n"                                                          >> "${PWD}/package.json"
  printf "  },\\n"                                                           >> "${PWD}/package.json"
  printf "  \"dependencies\": {\\n"                                          >> "${PWD}/package.json"
  printf "    \"@opam/dune\": \"*\",\\n"                                     >> "${PWD}/package.json"
  printf "    \"@esy-ocaml/reason\": \"*\",\\n"                              >> "${PWD}/package.json"
  printf "    \"refmterr\": \"*\",\\n"                                       >> "${PWD}/package.json"
  printf "    \"ocaml\": \"~4.6.0\",\\n"                                      >> "${PWD}/package.json"
  printf "    \"pesy\": \"*\"\\n"                                           >> "${PWD}/package.json"
  printf "  },\\n"                                                           >> "${PWD}/package.json"
  printf "  \"devDependencies\": {\\n"                                       >> "${PWD}/package.json"
  printf "    \"@esy-ocaml/merlin\": \"*\",\\n"                              >> "${PWD}/package.json"
  printf "    \"ocaml\": \"~4.6.0\"\\n"                                      >> "${PWD}/package.json"
  printf "  }\\n"                                                            >> "${PWD}/package.json"
  printf "}\\n"                                                              >> "${PWD}/package.json"


  printf "\\n%sSuccess!%s Created %s\\n\\n" "${BOLD}${GREEN}" "${RESET}" "${PWD}/package.json"
  printf "Now, run:\\n"
  printf "\\n"
  printf "    esy install\\n"
  printf "    esy build\\n"
  printf "\\n"
  exit 0
fi

set -u

PACKAGE_NAME="${cur__name}"
echo ""
echo "${BOLD}${PACKAGE_NAME}@${cur__version}${RESET}"

# Gnu uppercasing extensions to sed don't exist on mac.
PACKAGE_NAME_CAMEL=$(echo "${PACKAGE_NAME}" | perl -pe 's/([a-z0-9])-([a-zA-Z0-9])/$1\U$2/g')
PACKAGE_NAME_CAMEL_UC=$(tr '[:lower:]' '[:upper:]' <<< "${PACKAGE_NAME_CAMEL:0:1}")${PACKAGE_NAME_CAMEL:1}
NAMESPACE="${PACKAGE_NAME_CAMEL_UC}"
PUBLIC_LIB_NAME="${PACKAGE_NAME}.lib"


GEN_EVERYTHING="${cur__target_dir}/genEverything.sh"
PESY_DIR_CACHE="${cur__target_dir}/pesyDirCache.txt"
GEN_MD5="${cur__target_dir}/packageJson.md5"
mkdir -p "${cur__target_dir}"

CUR_MD5="${RANDOM}"

if [ -x "$(command -v md5)" ]; then
  CUR_MD5=$(md5 "${cur__root}/package.json")
else
  if [ -x "$(command -v md5sum)" ]; then
    CUR_MD5=$(md5sum "${cur__root}/package.json")
  else
    echo "Aborting build because no checksum utilities are found (md5/md5sum)"
    exit 1
  fi
fi

if [ -f  "${GEN_MD5}" ]; then
  PREV_MD5=$(cat "${GEN_MD5}")
else
  PREV_MD5=""
fi
printf "%s" "${CUR_MD5}" > "${GEN_MD5}"


if [[ "$CUR_MD5" == "$PREV_MD5" ]]; then
  "${GEN_EVERYTHING}"
  exit 0
fi

echo "" > "${GEN_EVERYTHING}"
chmod 777 "${GEN_EVERYTHING}"

# It can be expensive to find the pesy implementation dir.
if [ -f  "${PESY_DIR_CACHE}" ]; then
  PESY_DIR=$(cat "${PESY_DIR_CACHE}")
else
  SOURCE="${BASH_SOURCE[0]}"
  while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    PESY_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$PESY_DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done
  PESY_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
  echo "${PESY_DIR}" >  "${PESY_DIR_CACHE}"
fi

cat "${PESY_DIR}/pesy-header.sh" >> "${GEN_EVERYTHING}"

cat <<EOT >> "${GEN_EVERYTHING}"
PACKAGE_NAME="${PACKAGE_NAME}"
PACKAGE_NAME_CAMEL_UC="${PACKAGE_NAME_CAMEL_UC}"
NAMESPACE="${NAMESPACE}"
PUBLIC_LIB_NAME="${PUBLIC_LIB_NAME}"
EOT

function genLib() {
  DIR="$1"
  LIB_NAME="$2"
  sed  -e "s;<DIR>;${DIR};g; s;<LIB_NAME>;${LIB_NAME};g" "${PESY_DIR}/pesy-genLib.template.sh"  >> "${GEN_EVERYTHING}"
}


# Generate the config updater per bin directory.
function genBin() {
  DIR="$1"
  EXE_NAME="$2"
  sed  -e "s;<DIR>;${DIR};g; s;<EXE_NAME>;${EXE_NAME};g" "${PESY_DIR}/pesy-genBin.template.sh"  >> "${GEN_EVERYTHING}"
}


# Hacky, but fast and v8-less parsing of the important field in json file.
# Spit out some variable names that are of the form <DIR>_FEATURE.
# Then that secondary script can access those variables in generated code.

OIFS=$IFS;


# Initial pass through all names to set some defaults.
ALL_DIR_TO_NAME=$("${PESY_DIR}/pesy-JSON.sh" < "${cur__root}/package.json" |  sed -n 's;\["buildDirs","\([^"]*\)","name"\][[:space:]]*"\([^"]*\)";\1=\2;p')
ALL_DIR_TO_NAME=$(printf "%s" "$ALL_DIR_TO_NAME" | tr -s '\n' '|')
if [ -z "${ALL_DIR_TO_NAME}" ]; then
  # By default, bin and lib
  ALL_DIR_TO_NAME="bin=${PACKAGE_NAME}.exe|lib=${PACKAGE_NAME}.lib|"
fi
IFS="|";
ALL_DIR_TO_NAME_ARR=($ALL_DIR_TO_NAME);
# Set deafults for each package before then overriding them.
SEEN_A_LIB="false"
for ((i=0; i<${#ALL_DIR_TO_NAME_ARR[@]}; ++i)); do
  IFS="=";
  DIR_AND_NAME="${ALL_DIR_TO_NAME_ARR[$i]}"
  DIR_AND_NAME_ARR=($DIR_AND_NAME);
  DIR=${DIR_AND_NAME_ARR[0]}
  NAME=${DIR_AND_NAME_ARR[1]}
  if [[ "${NAME}" == *.lib ]]; then 
    # We will let a single library default to the namespace of the package.
    if [[ "${SEEN_A_LIB}" == "false" ]]; then
      echo "#Default Namespace" >> "${GEN_EVERYTHING}"
      echo "${DIR}_NAMESPACE=\"${PACKAGE_NAME_CAMEL_UC}\"" >> "${GEN_EVERYTHING}"
    else
      # Else if there's more than one lib each must set their namespace.
      echo "#Default Namespace, When More Than One Library Present" >> "${GEN_EVERYTHING}"
      echo "${DIR}_NAMESPACE=\"\"" >> "${GEN_EVERYTHING}"
    fi
    SEEN_A_LIB="true"
  fi
  echo "#Default Requires" >> "${GEN_EVERYTHING}"
  echo "${DIR}_REQUIRE=\"\"" >> "${GEN_EVERYTHING}"
  echo "#Default Flags" >> "${GEN_EVERYTHING}"
  echo "${DIR}_FLAGS=\"\"" >> "${GEN_EVERYTHING}"
  echo "${DIR}_OCAMLC_FLAGS=\"\"" >> "${GEN_EVERYTHING}"
  echo "${DIR}_OCAMLOPT_FLAGS=\"\"" >> "${GEN_EVERYTHING}"
done



ALL_DIR_TO_NAMESPACE=$("${PESY_DIR}/pesy-JSON.sh" < "${cur__root}/package.json" |  sed -n 's;\["buildDirs","\([^"]*\)","namespace"\][[:space:]]*\(.*\);\1=\2;p')
ALL_DIR_TO_NAMESPACE=$(printf "%s" "$ALL_DIR_TO_NAMESPACE" | tr -s '\n' '|')
IFS="|";
ALL_DIR_TO_NAMESPACE_ARR=($ALL_DIR_TO_NAMESPACE);
for ((i=0; i<${#ALL_DIR_TO_NAMESPACE_ARR[@]}; ++i)); do
  IFS="=";
  DIR_AND_NAMESPACE="${ALL_DIR_TO_NAMESPACE_ARR[$i]}"
  DIR_AND_NAMESPACE_ARR=($DIR_AND_NAMESPACE);
  DIR=${DIR_AND_NAMESPACE_ARR[0]}
  NAMESPACE=${DIR_AND_NAMESPACE_ARR[1]}
  echo "${DIR}_NAMESPACE=\"${NAMESPACE}\"" >> "${GEN_EVERYTHING}"
done

ALL_DIR_TO_MAIN=$("${PESY_DIR}/pesy-JSON.sh" < "${cur__root}/package.json" |  sed -n 's;\["buildDirs","\([^"]*\)","main"\][[:space:]]*\(.*\);\1=\2;p')
ALL_DIR_TO_MAIN=$(printf "%s" "$ALL_DIR_TO_MAIN" | tr -s '\n' '|')
IFS="|";
ALL_DIR_TO_MAIN_ARR=($ALL_DIR_TO_MAIN);
for ((i=0; i<${#ALL_DIR_TO_MAIN_ARR[@]}; ++i)); do
  IFS="=";
  DIR_AND_MAIN="${ALL_DIR_TO_MAIN_ARR[$i]}"
  DIR_AND_MAIN_ARR=($DIR_AND_MAIN);
  DIR=${DIR_AND_MAIN_ARR[0]}
  MAIN=${DIR_AND_MAIN_ARR[1]}
  echo "${DIR}_MAIN_MODULE=\"${MAIN}\"" >> "${GEN_EVERYTHING}"
done

ALL_DIR_TO_REQUIRE=$("${PESY_DIR}/pesy-JSON.sh" < "${cur__root}/package.json" |  sed -n 's;\["buildDirs","\([^"]*\)","require"\][[:space:]]*\(.*\);\1=\2;p')
ALL_DIR_TO_REQUIRE=$(printf "$ALL_DIR_TO_REQUIRE" | tr -s '["],' ' ')
ALL_DIR_TO_REQUIRE=$(printf "%s" "$ALL_DIR_TO_REQUIRE" | tr -s '\n' '|')
IFS="|";
ALL_DIR_TO_REQUIRE_ARR=($ALL_DIR_TO_REQUIRE);
for ((i=0; i<${#ALL_DIR_TO_REQUIRE_ARR[@]}; ++i)); do
  IFS="=";
  DIR_AND_REQUIRE="${ALL_DIR_TO_REQUIRE_ARR[$i]}"
  DIR_AND_REQUIRE_ARR=($DIR_AND_REQUIRE);
  DIR=${DIR_AND_REQUIRE_ARR[0]}
  REQUIRE=${DIR_AND_REQUIRE_ARR[1]}
  # This one is an array so we take an extra step to strip out [ ] and ""
  echo "${DIR}_REQUIRE=\"${REQUIRE}\"" >> "${GEN_EVERYTHING}"
done

ALL_DIR_TO_FLAGS=$("${PESY_DIR}/pesy-JSON.sh" < "${cur__root}/package.json" |  sed -n 's;\["buildDirs","\([^"]*\)","flags"\][[:space:]]*\(.*\);\1=\2;p')
ALL_DIR_TO_FLAGS=$(printf "$ALL_DIR_TO_FLAGS" | tr -s '["],' ' ')
ALL_DIR_TO_FLAGS=$(printf "%s" "$ALL_DIR_TO_FLAGS" | tr -s '\n' '|')
IFS="|";
ALL_DIR_TO_FLAGS_ARR=($ALL_DIR_TO_FLAGS);
for ((i=0; i<${#ALL_DIR_TO_FLAGS_ARR[@]}; ++i)); do
  IFS="=";
  DIR_AND_FLAGS="${ALL_DIR_TO_FLAGS_ARR[$i]}"
  DIR_AND_FLAGS_ARR=($DIR_AND_FLAGS);
  DIR=${DIR_AND_FLAGS_ARR[0]}
  FLAGS=${DIR_AND_FLAGS_ARR[1]}
  # This one is an array so we take an extra step to strip out [ ] and ""
  echo "${DIR}_FLAGS=\"${FLAGS}\"" >> "${GEN_EVERYTHING}"
done

ALL_DIR_TO_OCAMLC_FLAGS=$("${PESY_DIR}/pesy-JSON.sh" < "${cur__root}/package.json" |  sed -n 's;\["buildDirs","\([^"]*\)","ocamlcFlags"\][[:space:]]*\(.*\);\1=\2;p')
ALL_DIR_TO_OCAMLC_FLAGS=$(printf "$ALL_DIR_TO_OCAMLC_FLAGS" | tr -s '["],' ' ')
ALL_DIR_TO_OCAMLC_FLAGS=$(printf "%s" "$ALL_DIR_TO_OCAMLC_FLAGS" | tr -s '\n' '|')
IFS="|";
ALL_DIR_TO_OCAMLC_FLAGS_ARR=($ALL_DIR_TO_OCAMLC_FLAGS);
for ((i=0; i<${#ALL_DIR_TO_OCAMLC_FLAGS_ARR[@]}; ++i)); do
  IFS="=";
  DIR_AND_OCAMLC_FLAGS="${ALL_DIR_TO_OCAMLC_FLAGS_ARR[$i]}"
  DIR_AND_OCAMLC_FLAGS_ARR=($DIR_AND_OCAMLC_FLAGS);
  DIR=${DIR_AND_OCAMLC_FLAGS_ARR[0]}
  FLAGS=${DIR_AND_OCAMLC_FLAGS_ARR[1]}
  # This one is an array so we take an extra step to strip out [ ] and ""
  echo "${DIR}_OCAMLC_FLAGS=\"${FLAGS}\"" >> "${GEN_EVERYTHING}"
done

ALL_DIR_TO_OCAMLOPT_FLAGS=$("${PESY_DIR}/pesy-JSON.sh" < "${cur__root}/package.json" |  sed -n 's;\["buildDirs","\([^"]*\)","ocamloptFlags"\][[:space:]]*\(.*\);\1=\2;p')
ALL_DIR_TO_OCAMLOPT_FLAGS=$(printf "$ALL_DIR_TO_OCAMLOPT_FLAGS" | tr -s '["],' ' ')
ALL_DIR_TO_OCAMLOPT_FLAGS=$(printf "%s" "$ALL_DIR_TO_OCAMLOPT_FLAGS" | tr -s '\n' '|')
IFS="|";
ALL_DIR_TO_OCAMLOPT_FLAGS_ARR=($ALL_DIR_TO_OCAMLOPT_FLAGS);
for ((i=0; i<${#ALL_DIR_TO_OCAMLOPT_FLAGS_ARR[@]}; ++i)); do
  IFS="=";
  DIR_AND_OCAMLOPT_FLAGS="${ALL_DIR_TO_OCAMLOPT_FLAGS_ARR[$i]}"
  DIR_AND_OCAMLOPT_FLAGS_ARR=($DIR_AND_OCAMLOPT_FLAGS);
  DIR=${DIR_AND_OCAMLOPT_FLAGS_ARR[0]}
  FLAGS=${DIR_AND_OCAMLOPT_FLAGS_ARR[1]}
  # This one is an array so we take an extra step to strip out [ ] and ""
  echo "${DIR}_OCAMLOPT_FLAGS=\"${FLAGS}\"" >> "${GEN_EVERYTHING}"
done

# Print a summary of each named target.
for ((i=0; i<${#ALL_DIR_TO_NAME_ARR[@]}; ++i)); do
  IFS="=";
  DIR_AND_NAME="${ALL_DIR_TO_NAME_ARR[$i]}"
  DIR_AND_NAME_ARR=($DIR_AND_NAME);
  DIR=${DIR_AND_NAME_ARR[0]}
  NAME=${DIR_AND_NAME_ARR[1]}
  if [[ "$i" == $(expr "${#ALL_DIR_TO_NAME_ARR[@]}" - "1") ]]; then
    IS_LAST="last"
  else
    IS_LAST="not-last"
  fi

  if [[ "${NAME}" == *.exe ]]; then 
    echo "printDirectory \"$DIR\" \"name:    $NAME\" \"main:    \${${DIR}_MAIN_MODULE:-\$DEFAULT_MAIN_MODULE_NAME}\" \"require:\$${DIR}_REQUIRE\"" "$IS_LAST" >> "$GEN_EVERYTHING"
  else
    if [[ "${NAME}" == "${PACKAGE_NAME}"\.* ]]; then 
      echo "printDirectory \"$DIR\" \"library name: $NAME\" \"namespace:    \$${DIR}_NAMESPACE\" \"require:     \$${DIR}_REQUIRE\"" "$IS_LAST" >> "$GEN_EVERYTHING"
    else
      # Errors will be caught later
      true
    fi
  fi
done

# Perform the updates/refresh per target or build.
for ((i=0; i<${#ALL_DIR_TO_NAME_ARR[@]}; ++i)); do
  IFS="=";
  DIR_AND_NAME="${ALL_DIR_TO_NAME_ARR[$i]}"
  DIR_AND_NAME_ARR=($DIR_AND_NAME);
  DIR=${DIR_AND_NAME_ARR[0]}
  NAME=${DIR_AND_NAME_ARR[1]}

  if [[ "${NAME}" == "" ]]; then 
    printf "\\n%sMisconfigured package.json:%s" "${RED}${BOLD}" "${RESET}"
    printf "\\n  - Missing/empty name for buildDirs/%s\\n\\n" "${DIR}"
    exit 1
  fi
  if [[ "${NAME}" == *.exe ]]; then 
    genBin "$DIR" "$NAME"
  else
    if [[ "${NAME}" == "${PACKAGE_NAME}"\.* ]]; then 
      genLib "$DIR" "$NAME"
    else
      printf "\\n%sMisconfigured package.json:%s" "${RED}${BOLD}" "${RESET}"
      printf "\\n"
      printf "\\n  buildDirs.%s.name (\"%s\")\\n" "${DIR}" "${NAME}" 
      printf "\\n  %s- Name should be any-name.exe to build a binary or%s" "${YELLOW}${BOLD}" "$RESET"
      printf "\\n  %s- Name should be %s.suffix to build a library, where 'suffix' is anything but 'exe'%s\\n\\n" "${YELLOW}${BOLD}" "${PACKAGE_NAME}" "$RESET"
      exit 1
    fi
  fi
done
IFS=$OIFS;

sed  -e "s;<DIR>;${DIR};g; s;<LIB_NAME>;${LIB_NAME};g" "${PESY_DIR}/pesy-footer.template.sh" >> "${GEN_EVERYTHING}"

"${GEN_EVERYTHING}"
